INSERT INTO clientes (nombre,apellido,email,create_at) VALUES ('Edwin Stive','Parrales','epro82@hotmail.com','2019-10-27'); 
INSERT INTO clientes (nombre,apellido,email,create_at) VALUES ('Maria','Vargas Peña','maria2@gmail.com','2019-10-27'); 
INSERT INTO clientes (nombre,apellido,email,create_at) VALUES ('Miriam','Vargas','epro82@hotmail.com','2019-10-27'); 
INSERT INTO clientes (nombre,apellido,email,create_at) VALUES ('Jamez','Cardona','jam@hotmail.com','2019-10-27'); 
INSERT INTO clientes (nombre,apellido,email,create_at) VALUES ('Lilina','Sifuentes','epro82@hotmail.com','2019-10-27'); 
INSERT INTO clientes (nombre,apellido,email,create_at) VALUES ('Ronaldiño','Gaucho','Gauicio@hotmail.com','2019-10-27'); 
INSERT INTO clientes (nombre,apellido,email,create_at) VALUES ('Silverio','Estrella','estrella@hotmail.com','2019-10-27'); 
INSERT INTO clientes (nombre,apellido,email,create_at) VALUES ('Element','Black','ep@hotmail.com','2019-10-27'); 
INSERT INTO clientes (nombre,apellido,email,create_at) VALUES ('Omar','Valencia','epro82@hotmail.com','2019-10-27'); 
INSERT INTO clientes (nombre,apellido,email,create_at) VALUES ('Aida','Merlano','colgate@hotmail.com','2019-10-27'); 
